stages:
  - e2e

variables:
  DOCKER_DRIVER: overlay2
  VITE_FE_BASE_URL: http://frontend:5173
  VITE_API_BASE_URL: https://backend:8080/api

e2e-tests:
  stage: e2e
  image: docker:24.0.2
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash curl docker-compose
  script:
    # Build frontend and backend locally in this job
    # - docker-compose -f docker-compose.ci.yml build
    - docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from playwright
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 1 day
  only:
    - merge_requests
    - main
