stages:
  - build
  - e2e

variables:
  DOCKER_DRIVER: overlay2
  VITE_FE_BASE_URL: http://frontend:5173

build-frontend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t my-frontend:local ./bet-exchange

build-backend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t my-backend:local ./Server

e2e-tests:
  stage: e2e
  image: docker:24.0.2
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash curl docker-compose
  script:
    - docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from playwright
  needs:
    - build-frontend
    - build-backend
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 1 day
  only:
    - merge_requests
    - main