stages:
  - build
  - e2e

variables:
  DOCKER_DRIVER: overlay2

build-frontend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t my-frontend:local ./bet-exchange

build-backend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t my-backend:local ./Server

e2e-tests:
  stage: e2e
  image: docker:24.0.2
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash curl docker-compose
  script:
    - docker-compose -f docker-compose.ci.yml up -d test-db backend frontend
    - bash -c 'for i in {1..10}; do curl -s http://backend:8080/actuator/health && break || sleep 5; done'
    - docker-compose -f docker-compose.ci.yml run --rm playwright
    - docker-compose -f docker-compose.ci.yml down
  needs:
    - build-frontend
    - build-backend
  only:
    - merge_requests
    - main