stages:
  - build
  - e2e

variables:
  DOCKER_DRIVER: overlay2

build-frontend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t my-frontend:local ./bet-exchange

build-backend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t my-backend:local ./Server

e2e-tests:
  image: mcr.microsoft.com/playwright:v1.52.0-noble
  services:
    - name: postgres:latest
      alias: test-db
    - name: my-backend:local
      alias: backend
      healthcheck:
        test: ["CMD", "curl", "-f", "http://backend:8080/actuator/health"]
        interval: 10s
        retries: 5
    - name: my-frontend:local
      alias: frontend
      healthcheck:
        test: ["CMD", "curl", "-f", "http://frontend:5173"]
        interval: 10s
        retries: 5
  variables:
    VITE_FE_BASE_URL: http://frontend:5173
    BACKEND_URL: http://backend:8080
  before_script:
    - npm ci
    - npx playwright install --with-deps
  script:
    - echo "Waiting for services…"; sleep 15
    - npx playwright test --config=playwright.config.ts --reporter=html
  artifacts:
    when: always
    paths:
      - playwright-report/