stages:
  - build
  - e2e

variables:
  DOCKER_DRIVER: overlay2
  VITE_FE_BASE_URL: http://frontend:5173

build-frontend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t my-frontend:local ./bet-exchange

build-backend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t my-backend:local ./Server

e2e-tests:
  stage: e2e
  image: mcr.microsoft.com/playwright:v1.52.0-noble
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose curl
    - docker-compose -f docker-compose.ci.yml up -d
    - echo "Waiting for backend to be ready..."
    - >
      timeout 60 sh -c '
        until curl -s http://backend:8080/actuator/health | grep UP; do
          echo "."; sleep 2;
        done'
    - echo "Waiting for frontend to be ready..."
    - >
      timeout 60 sh -c '
        until curl -s http://frontend:5173 | grep -q "<!doctype html>"; do
          echo "."; sleep 2;
        done'
    - npm ci
    - npx playwright install --with-deps
    - npx playwright install msedge
    - npx playwright test --config=playwright.config.ts
    - docker-compose -f docker-compose.ci.yml down
  needs:
    - build-frontend
    - build-backend
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 1 day
  only:
    - merge_requests
    - main