stages:
  - build
  - test
  - e2e

variables:
  DOCKER_DRIVER: overlay2

build-frontend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t my-frontend:local ./bet-exchange

build-backend:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t my-backend:local ./Server

e2e-tests:
  stage: e2e
  image: mcr.microsoft.com/playwright:v1.52.0-noble
  services:
    - docker:dind
  before_script:
    - apt-get update && apt-get install -y curl docker-compose
    - docker-compose -f docker-compose.ci.yml up -d --build
    - echo "Waiting for backend to be ready..."
    - bash -c 'for i in {1..10}; do curl -s http://backend:8080/actuator/health && break || sleep 5; done'
  script:
    - cd bet-exchange
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test --config=playwright.config.ts
  after_script:
    - docker-compose -f docker-compose.ci.yml down
  artifacts:
    when: always
    paths:
      - bet-exchange/playwright-report/
  only:
    - merge_requests
    - main
