services:
  test-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    networks:
      - test-net

  backend:
    image: my-backend:local
    build:
      context: ./Server
      dockerfile: Dockerfile
    depends_on:
      - test-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://test-db:5432/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass
      SPRING_PROFILES_ACTIVE: test
    networks:
      - test-net
    ports:
      - "8080:8080"

  frontend:
    image: my-frontend:local
    build:
      context: ./bet-exchange
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - test-net
    ports:
      - "5173:5173"

  playwright:
    image: mcr.microsoft.com/playwright:v1.52.0-noble
    depends_on:
      - frontend
      - backend
    networks:
      - test-net
    working_dir: /tests
    volumes:
      - ./bet-exchange:/tests
      - /dev/shm:/dev/shm
    entrypoint:
      - "npx"
      - "playwright"
      - "test"
      - "--config=playwright.config.ts"
    # exit code of this service will reflect test success/failure

networks:
  test-net:
    driver: bridge
